theory-action: style, add error message

diff --git a/bin/theory-action.in b/bin/theory-action.in
--- a/bin/theory-action.in
+++ b/bin/theory-action.in
@@ -32,8 +32,10 @@ while [ "$#" -gt 0 ]; do
 		done
 	fi
 
-	if test -r "${1}"/action -a -s "${1}"/action && \
-		! { sh -n "${1}"/action && cat "${1}"/action  }; then
+	if test -r "${1}"/action -a -s "${1}"/action; then
+		sh -n "${1}"/action || error -d "syntax error in '%s', dying\n" "${1}/action"
+		cat "${1}"/action
+	else
 		exit
 	fi
 
