style: switch to using 4 space indentation again

diff --git a/lib/flow.sh.in b/lib/flow.sh.in
--- a/lib/flow.sh.in
+++ b/lib/flow.sh.in
@@ -2,84 +2,84 @@
 
 # shellcheck disable=SC2154
 if [ -z "${NO_COLOR}" ]; then
-	color_red=$(printf '\e[31m')    # $(tput setaf 1)
-	color_green=$(printf '\e[32m')  # $(tput setaf 2)
-	color_yellow=$(printf '\e[33m') # $(tput setaf 3)
-	color_bold=$(printf '\e[1m')    # $(tput bold)
-	color_reset=$(printf '\e[0m')   # $(tput sgr0)
+    color_red=$(printf '\e[31m')    # $(tput setaf 1)
+    color_green=$(printf '\e[32m')  # $(tput setaf 2)
+    color_yellow=$(printf '\e[33m') # $(tput setaf 3)
+    color_bold=$(printf '\e[1m')    # $(tput bold)
+    color_reset=$(printf '\e[0m')   # $(tput sgr0)
 fi
 
 pdo() {
-	local dry_run=false die=true
+    local dry_run=false die=true
 
-	# NOTE(somasis): string slicing would make this nicer and more obvious,
-	#                but that is a bash/mksh extension.
-	while [ $# -gt 0 ]; do
-		case "$1" in
-			-*)
-				:
-				;;
-			*)
-				break
-				;;
-		esac
+    # NOTE(somasis): string slicing would make this nicer and more obvious,
+    #                but that is a bash/mksh extension.
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -*)
+                :
+                ;;
+            *)
+                break
+                ;;
+        esac
 
-		case "$1" in
-			-n)
-				local dry_run=true
-				;;
-			-d)
-				local die=false
-				;;
-		esac
-		shift
-	done
+        case "$1" in
+            -n)
+                local dry_run=true
+                ;;
+            -d)
+                local die=false
+                ;;
+        esac
+        shift
+    done
 
-	pstderr "+ %s\n" "$*"
-	if ! "${dry_run}"; then
-		"$@" || {
-			err_code=$?
-			"${die}" && perror -d "command \`%s\` exited with %s\n" "$*" "${err_code}"
-		}
-	fi
+    pstderr "+ %s\n" "$*"
+    if ! "${dry_run}"; then
+        "$@" || {
+            err_code=$?
+            "${die}" && perror -d "command \`%s\` exited with %s\n" "$*" "${err_code}"
+        }
+    fi
 }
 
 # Ignore warning about arguments never being passed to pdie.
 # shellcheck disable=SC2120
 pdie() {
-	[ "$#" -gt 0 ] && pstderr "$@"
-	exit 1
+    [ "$#" -gt 0 ] && pstderr "$@"
+    exit 1
 }
 
 perror() {
-	local die=false
-	case "${1}" in
-		-d)
-			die=true
-			shift
-			;;
-	esac
+    local die=false
+    case "${1}" in
+        -d)
+            die=true
+            shift
+            ;;
+    esac
 
-	local msg="${1}"
-	shift
-	pstderr "${color_bold}${color_red}!!${color_reset} ${msg}" "$@"
+    local msg="${1}"
+    shift
+    pstderr "${color_bold}${color_red}!!${color_reset} ${msg}" "$@"
 
-	"${die}" && pdie
+    "${die}" && pdie
 }
 
 pwarning() {
-	local msg="${1}"
-	shift
-	pstderr "${color_bold}${color_yellow}!?${color_reset} ${msg}" "$@"
+    local msg="${1}"
+    shift
+    pstderr "${color_bold}${color_yellow}!?${color_reset} ${msg}" "$@"
 }
 
 pinfo() {
-	local msg="${1}"
-	shift
-	pstderr "${color_bold}${color_green}..${color_reset} ${msg}" "$@"
+    local msg="${1}"
+    shift
+    pstderr "${color_bold}${color_green}..${color_reset} ${msg}" "$@"
 }
 
 pstderr() {
-	# shellcheck disable=SC2059
-	printf "$@" >&2
+    # shellcheck disable=SC2059
+    printf "$@" >&2
 }
