lib/flow.sh edo(): die by default, make -d disable it

diff --git a/lib/flow.sh.in b/lib/flow.sh.in
--- a/lib/flow.sh.in
+++ b/lib/flow.sh.in
@@ -7,14 +7,14 @@ if [ -z "${NO_COLOR}" ]; then
 fi
 
 edo() {
-	local dry_run=false die=false arg
+	local dry_run=false die=true arg
 	while [ $# -gt 0 ] && [ "${1:0:1}" = '-' ]; do
 		case "$1" in
 			-n)
 				local dry_run=true
 				;;
 			-d)
-				local die=true
+				local die=false
 				;;
 		esac
 		shift
@@ -22,10 +22,7 @@ edo() {
 
 	stderr "+ %s\n" "$*"
 	if ! "${dry_run}"; then
-		if ! "$@" && "${die}"; then
-			err_code="$?"
-			"${die}" && error -d "command \`%s\` exited with %s\n" "$*" "$?"
-		fi
+		"$@" || { err_code=$?; "${die}" && error -d "command \`%s\` exited with %s\n" "$*" "${err_code}"; }
 	fi
 }
 
